# Generated by Django 6.0.2 on 2026-09-24 20:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=120)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('is_manager', models.BooleanField(default=False)),
                ('work_country', models.CharField(max_length=2)),
                ('work_state', models.CharField(blank=True, max_length=2)),
                ('work_location', models.CharField(max_length=120)),
                ('is_remote', models.BooleanField(default=False)),
                ('annual_salary_cents', models.BigIntegerField()),
                ('pay_currency', models.CharField(default='USD', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('requested_by', models.CharField(max_length=120)),
                ('new_job_title', models.CharField(max_length=120)),
                ('new_department', models.CharField(max_length=120)),
                ('new_level', models.PositiveSmallIntegerField()),
                ('new_is_manager', models.BooleanField(default=False)),
                ('new_work_country', models.CharField(max_length=2)),
                ('new_work_state', models.CharField(blank=True, max_length=2)),
                ('new_work_location', models.CharField(max_length=120)),
                ('new_is_remote', models.BooleanField(default=False)),
                ('new_annual_salary_cents', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_changes', to='employee_lifecycle.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_type', models.CharField(default='employee_role_location_change', max_length=80)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('current_step', models.CharField(blank=True, max_length=80)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('previous_state', models.JSONField(default=dict)),
                ('context', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_run', to='employee_lifecycle.rolechangerequest')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStepRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('result', models.JSONField(default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='employee_lifecycle.workflowrun')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('run', 'name')},
            },
        ),
    ]
